name: Deploy Flow Guard

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: deploy-flow-guard-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: false

jobs:
  guard-stg:
    name: stg
    if: ${{ github.event.pull_request.base.ref == 'stg' }}
    runs-on: self-hosted
    steps:
      - name: Enforce dev -> stg
        shell: bash
        run: |
          set -euo pipefail
          HEAD="${{ github.event.pull_request.head.ref }}"
          if [ "$HEAD" != "dev" ]; then
            echo "::error title=Blocked PR::PR para 'stg' só é permitido a partir de 'dev' (recebido de '$HEAD')."
            exit 1
          fi
          echo "Fluxo permitido (dev -> stg) ✔"

  guard-main:
    name: main
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    runs-on: self-hosted
    steps:
      - name: Enforce stg -> main
        shell: bash
        run: |
          set -euo pipefail
          HEAD="${{ github.event.pull_request.head.ref }}"
          if [ "$HEAD" != "stg" ]; then
            echo "::error title=Blocked PR::PR para 'main' só é permitido a partir de 'stg' (recebido de '$HEAD')."
            exit 1
          fi
          echo "Fluxo permitido (stg -> main) ✔"
